name: Build and deploy .NET Core application to Web App SampleWebAppSite
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: SampleWebAppSite
  AZURE_WEBAPP_PACKAGE_PATH: TestProject\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: TestProject
  OCTOPUS_URL: 'https://cic.octopus.app'
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_SPACE: Default
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Create ZIP package
      run: |
          cd ./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip -r TestProject1.0.1.zip .
          mv TestProject1.0.1.zip ../TestProject1.0.1.zip
    - name: Install Octopus CLI 🐙
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: "*"
    - name: Push build information to Octopus Deploy 🐙
      uses: OctopusDeploy/push-build-information-action@v3
      with:
        packages: |
          'my-dotnet-artifacts'
        version: 1.0.1
    - name: Push a package to Octopus Deploy 🐙
      uses: OctopusDeploy/push-package-action@v3
      with:
        packages: my-dotnet-artifacts1.0.1.zip
        overwrite_mode: OverwriteExisting
    - name: Create a release in Octopus Deploy 🐙
      uses: OctopusDeploy/create-release-action@v3
      with:
        project: 'CICProject'
        release_number: '1.0.1'
    - name: Deploy a release in Octopus Deploy 🐙
      uses: OctopusDeploy/deploy-release-action@v3
      with:
        project: 'CICProject'
        release_number: '1.0.1'
        environments: 'QA'  
          
          
          
          
          
          
          
          
          
          
          
          
          
